*--------------------------------------------------------------------------------------------------------------------------------------------------------
* (ES) AUTOGENERADO - ¡¡ATENCIÓN!! - ¡¡NO PENSADO PARA EJECUTAR!! USAR SOLAMENTE PARA INTEGRAR CAMBIOS Y ALMACENAR CON HERRAMIENTAS SCM!!
* (EN) AUTOGENERATED - ATTENTION!! - NOT INTENDED FOR EXECUTION!! USE ONLY FOR MERGING CHANGES AND STORING WITH SCM TOOLS!!
*--------------------------------------------------------------------------------------------------------------------------------------------------------
*< FOXBIN2PRG: Version="1.19" SourceFile="categories.dbf" /> (Solo para binarios VFP 9 / Only for VFP 9 binaries)
*


<TABLE>
	<MemoFile></MemoFile>
	<CodePage>1252</CodePage>
	<LastUpdate></LastUpdate>
	<Database>northwind.dbc</Database>
	<FileType>0x00000031</FileType>
	<FileType_Descrip>Visual FoxPro, autoincrement enabled</FileType_Descrip>

	<FIELDS>
		<FIELD>
			<Name>CATEGORYID</Name>
			<Type>I</Type>
			<Width>4</Width>
			<Decimals>0</Decimals>
			<Null>.F.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName>CATEGORIES</LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp>__ri_update_categories()</Upd_Trig_Exp>
			<Del_Trig_Exp>__ri_delete_categories()</Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>10</Autoinc_Nextval>
			<Autoinc_Step>1</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>CATEGORYNAME</Name>
			<Type>C</Type>
			<Width>15</Width>
			<Decimals>0</Decimals>
			<Null>.F.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>DESCRIPTION</Name>
			<Type>M</Type>
			<Width>4</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>PICTURE</Name>
			<Type>G</Type>
			<Width>4</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
	</FIELDS>


	<indexFile>CATEGORIES.CDX</indexFile>

	<INDEXES>
		<INDEX>
			<TagName>CATEGORYID</TagName>
			<TagType>PRIMARY</TagType>
			<Key>CATEGORYID</Key>
			<Filter></Filter>
			<Order>ASCENDING</Order>
			<Collate>MACHINE</Collate>
		</INDEX>
		<INDEX>
			<TagName>CATEGORYNM</TagName>
			<TagType>REGULAR</TagType>
			<Key>UPPER(CATEGORYNAME)</Key>
			<Filter></Filter>
			<Order>ASCENDING</Order>
			<Collate>MACHINE</Collate>
		</INDEX>
	</INDEXES>



	<RECORDS>

		<RECORD>
			<CATEGORYID>1</CATEGORYID>
			<CATEGORYNAME>Beverages</CATEGORYNAME>
			<DESCRIPTION><![CDATA[Soft drinks, coffees, teas, beers, and ales]]></DESCRIPTION>
		</RECORD>

		<RECORD>
			<CATEGORYID>2</CATEGORYID>
			<CATEGORYNAME>Condiments</CATEGORYNAME>
			<DESCRIPTION><![CDATA[Sweet and savory sauces, relishes, spreads, and seasonings]]></DESCRIPTION>
		</RECORD>

		<RECORD>
			<CATEGORYID>3</CATEGORYID>
			<CATEGORYNAME>Confections</CATEGORYNAME>
			<DESCRIPTION><![CDATA[Desserts, candies, and sweet breads]]></DESCRIPTION>
		</RECORD>

		<RECORD>
			<CATEGORYID>4</CATEGORYID>
			<CATEGORYNAME>Dairy Products</CATEGORYNAME>
			<DESCRIPTION><![CDATA[Cheeses]]></DESCRIPTION>
		</RECORD>

		<RECORD>
			<CATEGORYID>5</CATEGORYID>
			<CATEGORYNAME>Grains&#47;Cereals</CATEGORYNAME>
			<DESCRIPTION><![CDATA[Breads, crackers, pasta, and cereal]]></DESCRIPTION>
		</RECORD>

		<RECORD>
			<CATEGORYID>6</CATEGORYID>
			<CATEGORYNAME>Meat&#47;Poultry</CATEGORYNAME>
			<DESCRIPTION><![CDATA[Prepared meats]]></DESCRIPTION>
		</RECORD>

		<RECORD>
			<CATEGORYID>7</CATEGORYID>
			<CATEGORYNAME>Produce</CATEGORYNAME>
			<DESCRIPTION><![CDATA[Dried fruit and bean curd]]></DESCRIPTION>
		</RECORD>

		<RECORD>
			<CATEGORYID>8</CATEGORYID>
			<CATEGORYNAME>Seafood</CATEGORYNAME>
			<DESCRIPTION><![CDATA[Seaweed and fish]]></DESCRIPTION>
		</RECORD>

	</RECORDS>


</TABLE>

