*--------------------------------------------------------------------------------------------------------------------------------------------------------
* (ES) AUTOGENERADO - ¡¡ATENCIÓN!! - ¡¡NO PENSADO PARA EJECUTAR!! USAR SOLAMENTE PARA INTEGRAR CAMBIOS Y ALMACENAR CON HERRAMIENTAS SCM!!
* (EN) AUTOGENERATED - ATTENTION!! - NOT INTENDED FOR EXECUTION!! USE ONLY FOR MERGING CHANGES AND STORING WITH SCM TOOLS!!
*--------------------------------------------------------------------------------------------------------------------------------------------------------
*< FOXBIN2PRG: Version="1.19" SourceFile="customers.dbf" /> (Solo para binarios VFP 9 / Only for VFP 9 binaries)
*


<TABLE>
	<MemoFile></MemoFile>
	<CodePage>1252</CodePage>
	<LastUpdate></LastUpdate>
	<Database>northwind.dbc</Database>
	<FileType>0x00000030</FileType>
	<FileType_Descrip>Visual FoxPro</FileType_Descrip>

	<FIELDS>
		<FIELD>
			<Name>CUSTOMERID</Name>
			<Type>C</Type>
			<Width>5</Width>
			<Decimals>0</Decimals>
			<Null>.F.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName>CUSTOMERS</LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp>__ri_update_customers()</Upd_Trig_Exp>
			<Del_Trig_Exp>__ri_delete_customers()</Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>COMPANYNAME</Name>
			<Type>C</Type>
			<Width>40</Width>
			<Decimals>0</Decimals>
			<Null>.F.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>CONTACTNAME</Name>
			<Type>C</Type>
			<Width>30</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>CONTACTTITLE</Name>
			<Type>C</Type>
			<Width>30</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>ADDRESS</Name>
			<Type>C</Type>
			<Width>60</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>CITY</Name>
			<Type>C</Type>
			<Width>15</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>REGION</Name>
			<Type>C</Type>
			<Width>15</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>POSTALCODE</Name>
			<Type>C</Type>
			<Width>10</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>COUNTRY</Name>
			<Type>C</Type>
			<Width>15</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>PHONE</Name>
			<Type>C</Type>
			<Width>24</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>FAX</Name>
			<Type>C</Type>
			<Width>24</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
	</FIELDS>


	<indexFile>CUSTOMERS.CDX</indexFile>

	<INDEXES>
		<INDEX>
			<TagName>CITY</TagName>
			<TagType>REGULAR</TagType>
			<Key>UPPER(CITY)</Key>
			<Filter></Filter>
			<Order>ASCENDING</Order>
			<Collate>MACHINE</Collate>
		</INDEX>
		<INDEX>
			<TagName>COMPANYNAM</TagName>
			<TagType>REGULAR</TagType>
			<Key>UPPER(COMPANYNAME)</Key>
			<Filter></Filter>
			<Order>ASCENDING</Order>
			<Collate>MACHINE</Collate>
		</INDEX>
		<INDEX>
			<TagName>CUSTOMERID</TagName>
			<TagType>PRIMARY</TagType>
			<Key>CUSTOMERID</Key>
			<Filter></Filter>
			<Order>ASCENDING</Order>
			<Collate>MACHINE</Collate>
		</INDEX>
		<INDEX>
			<TagName>POSTALCODE</TagName>
			<TagType>REGULAR</TagType>
			<Key>UPPER(POSTALCODE)</Key>
			<Filter></Filter>
			<Order>ASCENDING</Order>
			<Collate>MACHINE</Collate>
		</INDEX>
		<INDEX>
			<TagName>REGION</TagName>
			<TagType>REGULAR</TagType>
			<Key>UPPER(REGION)</Key>
			<Filter></Filter>
			<Order>ASCENDING</Order>
			<Collate>MACHINE</Collate>
		</INDEX>
	</INDEXES>



	<RECORDS>

		<RECORD>
			<CUSTOMERID>ALFKI</CUSTOMERID>
			<COMPANYNAME>Alfreds Futterkiste</COMPANYNAME>
			<CONTACTNAME>Maria Anders</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>Obere Str. 57</ADDRESS>
			<CITY>Berlin</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>12209</POSTALCODE>
			<COUNTRY>Germany</COUNTRY>
			<PHONE>030-0074321</PHONE>
			<FAX>030-0076545</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>ANATR</CUSTOMERID>
			<COMPANYNAME>Ana Trujillo Emparedados y helados</COMPANYNAME>
			<CONTACTNAME>Ana Trujillo</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>Avda. de la Constitución 2222</ADDRESS>
			<CITY>México D.F.</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>05021</POSTALCODE>
			<COUNTRY>Mexico</COUNTRY>
			<PHONE>(5) 555-4729</PHONE>
			<FAX>(5) 555-3745</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>ANTON</CUSTOMERID>
			<COMPANYNAME>Antonio Moreno Taquería</COMPANYNAME>
			<CONTACTNAME>Antonio Moreno</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>Mataderos  2312</ADDRESS>
			<CITY>México D.F.</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>05023</POSTALCODE>
			<COUNTRY>Mexico</COUNTRY>
			<PHONE>(5) 555-3932</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>AROUT</CUSTOMERID>
			<COMPANYNAME>Around the Horn</COMPANYNAME>
			<CONTACTNAME>Thomas Hardy</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>120 Hanover Sq.</ADDRESS>
			<CITY>London</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>WA1 1DP</POSTALCODE>
			<COUNTRY>UK</COUNTRY>
			<PHONE>(171) 555-7788</PHONE>
			<FAX>(171) 555-6750</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>BERGS</CUSTOMERID>
			<COMPANYNAME>Berglunds snabbköp</COMPANYNAME>
			<CONTACTNAME>Christina Berglund</CONTACTNAME>
			<CONTACTTITLE>Order Administrator</CONTACTTITLE>
			<ADDRESS>Berguvsvägen  8</ADDRESS>
			<CITY>Luleå</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>S-958 22</POSTALCODE>
			<COUNTRY>Sweden</COUNTRY>
			<PHONE>0921-12 34 65</PHONE>
			<FAX>0921-12 34 67</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>BLAUS</CUSTOMERID>
			<COMPANYNAME>Blauer See Delikatessen</COMPANYNAME>
			<CONTACTNAME>Hanna Moos</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>Forsterstr. 57</ADDRESS>
			<CITY>Mannheim</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>68306</POSTALCODE>
			<COUNTRY>Germany</COUNTRY>
			<PHONE>0621-08460</PHONE>
			<FAX>0621-08924</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>BLONP</CUSTOMERID>
			<COMPANYNAME>Blondesddsl père et fils</COMPANYNAME>
			<CONTACTNAME>Frédérique Citeaux</CONTACTNAME>
			<CONTACTTITLE>Marketing Manager</CONTACTTITLE>
			<ADDRESS>24, place Kléber</ADDRESS>
			<CITY>Strasbourg</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>67000</POSTALCODE>
			<COUNTRY>France</COUNTRY>
			<PHONE>88.60.15.31</PHONE>
			<FAX>88.60.15.32</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>BOLID</CUSTOMERID>
			<COMPANYNAME>Bólido Comidas preparadas</COMPANYNAME>
			<CONTACTNAME>Martín Sommer</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>C&#47; Araquil, 67</ADDRESS>
			<CITY>Madrid</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>28023</POSTALCODE>
			<COUNTRY>Spain</COUNTRY>
			<PHONE>(91) 555 22 82</PHONE>
			<FAX>(91) 555 91 99</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>BONAP</CUSTOMERID>
			<COMPANYNAME>Bon app&#39;</COMPANYNAME>
			<CONTACTNAME>Laurence Lebihan</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>12, rue des Bouchers</ADDRESS>
			<CITY>Marseille</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>13008</POSTALCODE>
			<COUNTRY>France</COUNTRY>
			<PHONE>91.24.45.40</PHONE>
			<FAX>91.24.45.41</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>BOTTM</CUSTOMERID>
			<COMPANYNAME>Bottom-Dollar Markets</COMPANYNAME>
			<CONTACTNAME>Elizabeth Lincoln</CONTACTNAME>
			<CONTACTTITLE>Accounting Manager</CONTACTTITLE>
			<ADDRESS>23 Tsawassen Blvd.</ADDRESS>
			<CITY>Tsawassen</CITY>
			<REGION>BC</REGION>
			<POSTALCODE>T2F 8M4</POSTALCODE>
			<COUNTRY>Canada</COUNTRY>
			<PHONE>(604) 555-4729</PHONE>
			<FAX>(604) 555-3745</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>BSBEV</CUSTOMERID>
			<COMPANYNAME>B&#39;s Beverages</COMPANYNAME>
			<CONTACTNAME>Victoria Ashworth</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>Fauntleroy Circus</ADDRESS>
			<CITY>London</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>EC2 5NT</POSTALCODE>
			<COUNTRY>UK</COUNTRY>
			<PHONE>(171) 555-1212</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>CACTU</CUSTOMERID>
			<COMPANYNAME>Cactus Comidas para llevar</COMPANYNAME>
			<CONTACTNAME>Patricio Simpson</CONTACTNAME>
			<CONTACTTITLE>Sales Agent</CONTACTTITLE>
			<ADDRESS>Cerrito 333</ADDRESS>
			<CITY>Buenos Aires</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>1010</POSTALCODE>
			<COUNTRY>Argentina</COUNTRY>
			<PHONE>(1) 135-5555</PHONE>
			<FAX>(1) 135-4892</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>CENTC</CUSTOMERID>
			<COMPANYNAME>Centro comercial Moctezuma</COMPANYNAME>
			<CONTACTNAME>Francisco Chang</CONTACTNAME>
			<CONTACTTITLE>Marketing Manager</CONTACTTITLE>
			<ADDRESS>Sierras de Granada 9993</ADDRESS>
			<CITY>México D.F.</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>05022</POSTALCODE>
			<COUNTRY>Mexico</COUNTRY>
			<PHONE>(5) 555-3392</PHONE>
			<FAX>(5) 555-7293</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>CHOPS</CUSTOMERID>
			<COMPANYNAME>Chop-suey Chinese</COMPANYNAME>
			<CONTACTNAME>Yang Wang</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>Hauptstr. 29</ADDRESS>
			<CITY>Bern</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>3012</POSTALCODE>
			<COUNTRY>Switzerland</COUNTRY>
			<PHONE>0452-076545</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>COMMI</CUSTOMERID>
			<COMPANYNAME>Comércio Mineiro</COMPANYNAME>
			<CONTACTNAME>Pedro Afonso</CONTACTNAME>
			<CONTACTTITLE>Sales Associate</CONTACTTITLE>
			<ADDRESS>Av. dos Lusíadas, 23</ADDRESS>
			<CITY>Sao Paulo</CITY>
			<REGION>SP</REGION>
			<POSTALCODE>05432-043</POSTALCODE>
			<COUNTRY>Brazil</COUNTRY>
			<PHONE>(11) 555-7647</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>CONSH</CUSTOMERID>
			<COMPANYNAME>Consolidated Holdings</COMPANYNAME>
			<CONTACTNAME>Elizabeth Brown</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>Berkeley Gardens 12  Brewery</ADDRESS>
			<CITY>London</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>WX1 6LT</POSTALCODE>
			<COUNTRY>UK</COUNTRY>
			<PHONE>(171) 555-2282</PHONE>
			<FAX>(171) 555-9199</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>DRACD</CUSTOMERID>
			<COMPANYNAME>Drachenblut Delikatessen</COMPANYNAME>
			<CONTACTNAME>Sven Ottlieb</CONTACTNAME>
			<CONTACTTITLE>Order Administrator</CONTACTTITLE>
			<ADDRESS>Walserweg 21</ADDRESS>
			<CITY>Aachen</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>52066</POSTALCODE>
			<COUNTRY>Germany</COUNTRY>
			<PHONE>0241-039123</PHONE>
			<FAX>0241-059428</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>DUMON</CUSTOMERID>
			<COMPANYNAME>Du monde entier</COMPANYNAME>
			<CONTACTNAME>Janine Labrune</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>67, rue des Cinquante Otages</ADDRESS>
			<CITY>Nantes</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>44000</POSTALCODE>
			<COUNTRY>France</COUNTRY>
			<PHONE>40.67.88.88</PHONE>
			<FAX>40.67.89.89</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>EASTC</CUSTOMERID>
			<COMPANYNAME>Eastern Connection</COMPANYNAME>
			<CONTACTNAME>Ann Devon</CONTACTNAME>
			<CONTACTTITLE>Sales Agent</CONTACTTITLE>
			<ADDRESS>35 King George</ADDRESS>
			<CITY>London</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>WX3 6FW</POSTALCODE>
			<COUNTRY>UK</COUNTRY>
			<PHONE>(171) 555-0297</PHONE>
			<FAX>(171) 555-3373</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>ERNSH</CUSTOMERID>
			<COMPANYNAME>Ernst Handel</COMPANYNAME>
			<CONTACTNAME>Roland Mendel</CONTACTNAME>
			<CONTACTTITLE>Sales Manager</CONTACTTITLE>
			<ADDRESS>Kirchgasse 6</ADDRESS>
			<CITY>Graz</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>8010</POSTALCODE>
			<COUNTRY>Austria</COUNTRY>
			<PHONE>7675-3425</PHONE>
			<FAX>7675-3426</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>FAMIA</CUSTOMERID>
			<COMPANYNAME>Familia Arquibaldo</COMPANYNAME>
			<CONTACTNAME>Aria Cruz</CONTACTNAME>
			<CONTACTTITLE>Marketing Assistant</CONTACTTITLE>
			<ADDRESS>Rua Orós, 92</ADDRESS>
			<CITY>Sao Paulo</CITY>
			<REGION>SP</REGION>
			<POSTALCODE>05442-030</POSTALCODE>
			<COUNTRY>Brazil</COUNTRY>
			<PHONE>(11) 555-9857</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>FISSA</CUSTOMERID>
			<COMPANYNAME>FISSA Fabrica Inter. Salchichas S.A.</COMPANYNAME>
			<CONTACTNAME>Diego Roel</CONTACTNAME>
			<CONTACTTITLE>Accounting Manager</CONTACTTITLE>
			<ADDRESS>C&#47; Moralzarzal, 86</ADDRESS>
			<CITY>Madrid</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>28034</POSTALCODE>
			<COUNTRY>Spain</COUNTRY>
			<PHONE>(91) 555 94 44</PHONE>
			<FAX>(91) 555 55 93</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>FOLIG</CUSTOMERID>
			<COMPANYNAME>Folies gourmandes</COMPANYNAME>
			<CONTACTNAME>Martine Rancé</CONTACTNAME>
			<CONTACTTITLE>Assistant Sales Agent</CONTACTTITLE>
			<ADDRESS>184, chaussée de Tournai</ADDRESS>
			<CITY>Lille</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>59000</POSTALCODE>
			<COUNTRY>France</COUNTRY>
			<PHONE>20.16.10.16</PHONE>
			<FAX>20.16.10.17</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>FOLKO</CUSTOMERID>
			<COMPANYNAME>Folk och fä HB</COMPANYNAME>
			<CONTACTNAME>Maria Larsson</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>Åkergatan 24</ADDRESS>
			<CITY>Bräcke</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>S-844 67</POSTALCODE>
			<COUNTRY>Sweden</COUNTRY>
			<PHONE>0695-34 67 21</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>FRANK</CUSTOMERID>
			<COMPANYNAME>Frankenversand</COMPANYNAME>
			<CONTACTNAME>Peter Franken</CONTACTNAME>
			<CONTACTTITLE>Marketing Manager</CONTACTTITLE>
			<ADDRESS>Berliner Platz 43</ADDRESS>
			<CITY>München</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>80805</POSTALCODE>
			<COUNTRY>Germany</COUNTRY>
			<PHONE>089-0877310</PHONE>
			<FAX>089-0877451</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>FRANR</CUSTOMERID>
			<COMPANYNAME>France restauration</COMPANYNAME>
			<CONTACTNAME>Carine Schmitt</CONTACTNAME>
			<CONTACTTITLE>Marketing Manager</CONTACTTITLE>
			<ADDRESS>54, rue Royale</ADDRESS>
			<CITY>Nantes</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>44000</POSTALCODE>
			<COUNTRY>France</COUNTRY>
			<PHONE>40.32.21.21</PHONE>
			<FAX>40.32.21.20</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>FRANS</CUSTOMERID>
			<COMPANYNAME>Franchi S.p.A.</COMPANYNAME>
			<CONTACTNAME>Paolo Accorti</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>Via Monte Bianco 34</ADDRESS>
			<CITY>Torino</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>10100</POSTALCODE>
			<COUNTRY>Italy</COUNTRY>
			<PHONE>011-4988260</PHONE>
			<FAX>011-4988261</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>FURIB</CUSTOMERID>
			<COMPANYNAME>Furia Bacalhau e Frutos do Mar</COMPANYNAME>
			<CONTACTNAME>Lino Rodriguez</CONTACTNAME>
			<CONTACTTITLE>Sales Manager</CONTACTTITLE>
			<ADDRESS>Jardim das rosas n. 32</ADDRESS>
			<CITY>Lisboa</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>1675</POSTALCODE>
			<COUNTRY>Portugal</COUNTRY>
			<PHONE>(1) 354-2534</PHONE>
			<FAX>(1) 354-2535</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>GALED</CUSTOMERID>
			<COMPANYNAME>Galería del gastrónomo</COMPANYNAME>
			<CONTACTNAME>Eduardo Saavedra</CONTACTNAME>
			<CONTACTTITLE>Marketing Manager</CONTACTTITLE>
			<ADDRESS>Rambla de Cataluña, 23</ADDRESS>
			<CITY>Barcelona</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>08022</POSTALCODE>
			<COUNTRY>Spain</COUNTRY>
			<PHONE>(93) 203 4560</PHONE>
			<FAX>(93) 203 4561</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>GODOS</CUSTOMERID>
			<COMPANYNAME>Godos Cocina Típica</COMPANYNAME>
			<CONTACTNAME>José Pedro Freyre</CONTACTNAME>
			<CONTACTTITLE>Sales Manager</CONTACTTITLE>
			<ADDRESS>C&#47; Romero, 33</ADDRESS>
			<CITY>Sevilla</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>41101</POSTALCODE>
			<COUNTRY>Spain</COUNTRY>
			<PHONE>(95) 555 82 82</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>GOURL</CUSTOMERID>
			<COMPANYNAME>Gourmet Lanchonetes</COMPANYNAME>
			<CONTACTNAME>André Fonseca</CONTACTNAME>
			<CONTACTTITLE>Sales Associate</CONTACTTITLE>
			<ADDRESS>Av. Brasil, 442</ADDRESS>
			<CITY>Campinas</CITY>
			<REGION>SP</REGION>
			<POSTALCODE>04876-786</POSTALCODE>
			<COUNTRY>Brazil</COUNTRY>
			<PHONE>(11) 555-9482</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>GREAL</CUSTOMERID>
			<COMPANYNAME>Great Lakes Food Market</COMPANYNAME>
			<CONTACTNAME>Howard Snyder</CONTACTNAME>
			<CONTACTTITLE>Marketing Manager</CONTACTTITLE>
			<ADDRESS>2732 Baker Blvd.</ADDRESS>
			<CITY>Eugene</CITY>
			<REGION>OR</REGION>
			<POSTALCODE>97403</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
			<PHONE>(503) 555-7555</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>GROSR</CUSTOMERID>
			<COMPANYNAME>GROSELLA-Restaurante</COMPANYNAME>
			<CONTACTNAME>Manuel Pereira</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>5ª Ave. Los Palos Grandes</ADDRESS>
			<CITY>Caracas</CITY>
			<REGION>DF</REGION>
			<POSTALCODE>1081</POSTALCODE>
			<COUNTRY>Venezuela</COUNTRY>
			<PHONE>(2) 283-2951</PHONE>
			<FAX>(2) 283-3397</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>HANAR</CUSTOMERID>
			<COMPANYNAME>Hanari Carnes</COMPANYNAME>
			<CONTACTNAME>Mario Pontes</CONTACTNAME>
			<CONTACTTITLE>Accounting Manager</CONTACTTITLE>
			<ADDRESS>Rua do Paço, 67</ADDRESS>
			<CITY>Rio de Janeiro</CITY>
			<REGION>RJ</REGION>
			<POSTALCODE>05454-876</POSTALCODE>
			<COUNTRY>Brazil</COUNTRY>
			<PHONE>(21) 555-0091</PHONE>
			<FAX>(21) 555-8765</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>HILAA</CUSTOMERID>
			<COMPANYNAME>HILARION-Abastos</COMPANYNAME>
			<CONTACTNAME>Carlos Hernández</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>Carrera 22 con Ave. Carlos Soublette #8-35</ADDRESS>
			<CITY>San Cristóbal</CITY>
			<REGION>Táchira</REGION>
			<POSTALCODE>5022</POSTALCODE>
			<COUNTRY>Venezuela</COUNTRY>
			<PHONE>(5) 555-1340</PHONE>
			<FAX>(5) 555-1948</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>HUNGC</CUSTOMERID>
			<COMPANYNAME>Hungry Coyote Import Store</COMPANYNAME>
			<CONTACTNAME>Yoshi Latimer</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>City Center Plaza 516 Main St.</ADDRESS>
			<CITY>Elgin</CITY>
			<REGION>OR</REGION>
			<POSTALCODE>97827</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
			<PHONE>(503) 555-6874</PHONE>
			<FAX>(503) 555-2376</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>HUNGO</CUSTOMERID>
			<COMPANYNAME>Hungry Owl All-Night Grocers</COMPANYNAME>
			<CONTACTNAME>Patricia McKenna</CONTACTNAME>
			<CONTACTTITLE>Sales Associate</CONTACTTITLE>
			<ADDRESS>8 Johnstown Road</ADDRESS>
			<CITY>Cork</CITY>
			<REGION>Co. Cork</REGION>
			<POSTALCODE>.NULL.</POSTALCODE>
			<COUNTRY>Ireland</COUNTRY>
			<PHONE>2967 542</PHONE>
			<FAX>2967 3333</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>ISLAT</CUSTOMERID>
			<COMPANYNAME>Island Trading</COMPANYNAME>
			<CONTACTNAME>Helen Bennett</CONTACTNAME>
			<CONTACTTITLE>Marketing Manager</CONTACTTITLE>
			<ADDRESS>Garden House Crowther Way</ADDRESS>
			<CITY>Cowes</CITY>
			<REGION>Isle of Wight</REGION>
			<POSTALCODE>PO31 7PJ</POSTALCODE>
			<COUNTRY>UK</COUNTRY>
			<PHONE>(198) 555-8888</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>KOENE</CUSTOMERID>
			<COMPANYNAME>Königlich Essen</COMPANYNAME>
			<CONTACTNAME>Philip Cramer</CONTACTNAME>
			<CONTACTTITLE>Sales Associate</CONTACTTITLE>
			<ADDRESS>Maubelstr. 90</ADDRESS>
			<CITY>Brandenburg</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>14776</POSTALCODE>
			<COUNTRY>Germany</COUNTRY>
			<PHONE>0555-09876</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>LACOR</CUSTOMERID>
			<COMPANYNAME>La corne d&#39;abondance</COMPANYNAME>
			<CONTACTNAME>Daniel Tonini</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>67, avenue de l&#39;Europe</ADDRESS>
			<CITY>Versailles</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>78000</POSTALCODE>
			<COUNTRY>France</COUNTRY>
			<PHONE>30.59.84.10</PHONE>
			<FAX>30.59.85.11</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>LAMAI</CUSTOMERID>
			<COMPANYNAME>La maison d&#39;Asie</COMPANYNAME>
			<CONTACTNAME>Annette Roulet</CONTACTNAME>
			<CONTACTTITLE>Sales Manager</CONTACTTITLE>
			<ADDRESS>1 rue Alsace-Lorraine</ADDRESS>
			<CITY>Toulouse</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>31000</POSTALCODE>
			<COUNTRY>France</COUNTRY>
			<PHONE>61.77.61.10</PHONE>
			<FAX>61.77.61.11</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>LAUGB</CUSTOMERID>
			<COMPANYNAME>Laughing Bacchus Wine Cellars</COMPANYNAME>
			<CONTACTNAME>Yoshi Tannamuri</CONTACTNAME>
			<CONTACTTITLE>Marketing Assistant</CONTACTTITLE>
			<ADDRESS>1900 Oak St.</ADDRESS>
			<CITY>Vancouver</CITY>
			<REGION>BC</REGION>
			<POSTALCODE>V3F 2K1</POSTALCODE>
			<COUNTRY>Canada</COUNTRY>
			<PHONE>(604) 555-3392</PHONE>
			<FAX>(604) 555-7293</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>LAZYK</CUSTOMERID>
			<COMPANYNAME>Lazy K Kountry Store</COMPANYNAME>
			<CONTACTNAME>John Steel</CONTACTNAME>
			<CONTACTTITLE>Marketing Manager</CONTACTTITLE>
			<ADDRESS>12 Orchestra Terrace</ADDRESS>
			<CITY>Walla Walla</CITY>
			<REGION>WA</REGION>
			<POSTALCODE>99362</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
			<PHONE>(509) 555-7969</PHONE>
			<FAX>(509) 555-6221</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>LEHMS</CUSTOMERID>
			<COMPANYNAME>Lehmanns Marktstand</COMPANYNAME>
			<CONTACTNAME>Renate Messner</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>Magazinweg 7</ADDRESS>
			<CITY>Frankfurt a.M.</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>60528</POSTALCODE>
			<COUNTRY>Germany</COUNTRY>
			<PHONE>069-0245984</PHONE>
			<FAX>069-0245874</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>LETSS</CUSTOMERID>
			<COMPANYNAME>Let&#39;s Stop N Shop</COMPANYNAME>
			<CONTACTNAME>Jaime Yorres</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>87 Polk St. Suite 5</ADDRESS>
			<CITY>San Francisco</CITY>
			<REGION>CA</REGION>
			<POSTALCODE>94117</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
			<PHONE>(415) 555-5938</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>LILAS</CUSTOMERID>
			<COMPANYNAME>LILA-Supermercado</COMPANYNAME>
			<CONTACTNAME>Carlos González</CONTACTNAME>
			<CONTACTTITLE>Accounting Manager</CONTACTTITLE>
			<ADDRESS>Carrera 52 con Ave. Bolívar #65-98 Llano Largo</ADDRESS>
			<CITY>Barquisimeto</CITY>
			<REGION>Lara</REGION>
			<POSTALCODE>3508</POSTALCODE>
			<COUNTRY>Venezuela</COUNTRY>
			<PHONE>(9) 331-6954</PHONE>
			<FAX>(9) 331-7256</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>LINOD</CUSTOMERID>
			<COMPANYNAME>LINO-Delicateses</COMPANYNAME>
			<CONTACTNAME>Felipe Izquierdo</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>Ave. 5 de Mayo Porlamar</ADDRESS>
			<CITY>I. de Margarita</CITY>
			<REGION>Nueva Esparta</REGION>
			<POSTALCODE>4980</POSTALCODE>
			<COUNTRY>Venezuela</COUNTRY>
			<PHONE>(8) 34-56-12</PHONE>
			<FAX>(8) 34-93-93</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>LONEP</CUSTOMERID>
			<COMPANYNAME>Lonesome Pine Restaurant</COMPANYNAME>
			<CONTACTNAME>Fran Wilson</CONTACTNAME>
			<CONTACTTITLE>Sales Manager</CONTACTTITLE>
			<ADDRESS>89 Chiaroscuro Rd.</ADDRESS>
			<CITY>Portland</CITY>
			<REGION>OR</REGION>
			<POSTALCODE>97219</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
			<PHONE>(503) 555-9573</PHONE>
			<FAX>(503) 555-9646</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>MAGAA</CUSTOMERID>
			<COMPANYNAME>Magazzini Alimentari Riuniti</COMPANYNAME>
			<CONTACTNAME>Giovanni Rovelli</CONTACTNAME>
			<CONTACTTITLE>Marketing Manager</CONTACTTITLE>
			<ADDRESS>Via Ludovico il Moro 22</ADDRESS>
			<CITY>Bergamo</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>24100</POSTALCODE>
			<COUNTRY>Italy</COUNTRY>
			<PHONE>035-640230</PHONE>
			<FAX>035-640231</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>MAISD</CUSTOMERID>
			<COMPANYNAME>Maison Dewey</COMPANYNAME>
			<CONTACTNAME>Catherine Dewey</CONTACTNAME>
			<CONTACTTITLE>Sales Agent</CONTACTTITLE>
			<ADDRESS>Rue Joseph-Bens 532</ADDRESS>
			<CITY>Bruxelles</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>B-1180</POSTALCODE>
			<COUNTRY>Belgium</COUNTRY>
			<PHONE>(02) 201 24 67</PHONE>
			<FAX>(02) 201 24 68</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>MEREP</CUSTOMERID>
			<COMPANYNAME>Mère Paillarde</COMPANYNAME>
			<CONTACTNAME>Jean Fresnière</CONTACTNAME>
			<CONTACTTITLE>Marketing Assistant</CONTACTTITLE>
			<ADDRESS>43 rue St. Laurent</ADDRESS>
			<CITY>Montréal</CITY>
			<REGION>Québec</REGION>
			<POSTALCODE>H1J 1C3</POSTALCODE>
			<COUNTRY>Canada</COUNTRY>
			<PHONE>(514) 555-8054</PHONE>
			<FAX>(514) 555-8055</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>MORGK</CUSTOMERID>
			<COMPANYNAME>Morgenstern Gesundkost</COMPANYNAME>
			<CONTACTNAME>Alexander Feuer</CONTACTNAME>
			<CONTACTTITLE>Marketing Assistant</CONTACTTITLE>
			<ADDRESS>Heerstr. 22</ADDRESS>
			<CITY>Leipzig</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>04179</POSTALCODE>
			<COUNTRY>Germany</COUNTRY>
			<PHONE>0342-023176</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>NORTS</CUSTOMERID>
			<COMPANYNAME>North&#47;South</COMPANYNAME>
			<CONTACTNAME>Simon Crowther</CONTACTNAME>
			<CONTACTTITLE>Sales Associate</CONTACTTITLE>
			<ADDRESS>South House 300 Queensbridge</ADDRESS>
			<CITY>London</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>SW7 1RZ</POSTALCODE>
			<COUNTRY>UK</COUNTRY>
			<PHONE>(171) 555-7733</PHONE>
			<FAX>(171) 555-2530</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>OCEAN</CUSTOMERID>
			<COMPANYNAME>Océano Atlántico Ltda.</COMPANYNAME>
			<CONTACTNAME>Yvonne Moncada</CONTACTNAME>
			<CONTACTTITLE>Sales Agent</CONTACTTITLE>
			<ADDRESS>Ing. Gustavo Moncada 8585 Piso 20-A</ADDRESS>
			<CITY>Buenos Aires</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>1010</POSTALCODE>
			<COUNTRY>Argentina</COUNTRY>
			<PHONE>(1) 135-5333</PHONE>
			<FAX>(1) 135-5535</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>OLDWO</CUSTOMERID>
			<COMPANYNAME>Old World Delicatessen</COMPANYNAME>
			<CONTACTNAME>Rene Phillips</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>2743 Bering St.</ADDRESS>
			<CITY>Anchorage</CITY>
			<REGION>AK</REGION>
			<POSTALCODE>99508</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
			<PHONE>(907) 555-7584</PHONE>
			<FAX>(907) 555-2880</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>OTTIK</CUSTOMERID>
			<COMPANYNAME>Ottilies Käseladen</COMPANYNAME>
			<CONTACTNAME>Henriette Pfalzheim</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>Mehrheimerstr. 369</ADDRESS>
			<CITY>Köln</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>50739</POSTALCODE>
			<COUNTRY>Germany</COUNTRY>
			<PHONE>0221-0644327</PHONE>
			<FAX>0221-0765721</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>PARIS</CUSTOMERID>
			<COMPANYNAME>Paris spécialités</COMPANYNAME>
			<CONTACTNAME>Marie Bertrand</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>265, boulevard Charonne</ADDRESS>
			<CITY>Paris</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>75012</POSTALCODE>
			<COUNTRY>France</COUNTRY>
			<PHONE>(1) 42.34.22.66</PHONE>
			<FAX>(1) 42.34.22.77</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>PERIC</CUSTOMERID>
			<COMPANYNAME>Pericles Comidas clásicas</COMPANYNAME>
			<CONTACTNAME>Guillermo Fernández</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>Calle Dr. Jorge Cash 321</ADDRESS>
			<CITY>México D.F.</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>05033</POSTALCODE>
			<COUNTRY>Mexico</COUNTRY>
			<PHONE>(5) 552-3745</PHONE>
			<FAX>(5) 545-3745</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>PICCO</CUSTOMERID>
			<COMPANYNAME>Piccolo und mehr</COMPANYNAME>
			<CONTACTNAME>Georg Pipps</CONTACTNAME>
			<CONTACTTITLE>Sales Manager</CONTACTTITLE>
			<ADDRESS>Geislweg 14</ADDRESS>
			<CITY>Salzburg</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>5020</POSTALCODE>
			<COUNTRY>Austria</COUNTRY>
			<PHONE>6562-9722</PHONE>
			<FAX>6562-9723</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>PRINI</CUSTOMERID>
			<COMPANYNAME>Princesa Isabel Vinhos</COMPANYNAME>
			<CONTACTNAME>Isabel de Castro</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>Estrada da saúde n. 58</ADDRESS>
			<CITY>Lisboa</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>1756</POSTALCODE>
			<COUNTRY>Portugal</COUNTRY>
			<PHONE>(1) 356-5634</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>QUEDE</CUSTOMERID>
			<COMPANYNAME>Que Delícia</COMPANYNAME>
			<CONTACTNAME>Bernardo Batista</CONTACTNAME>
			<CONTACTTITLE>Accounting Manager</CONTACTTITLE>
			<ADDRESS>Rua da Panificadora, 12</ADDRESS>
			<CITY>Rio de Janeiro</CITY>
			<REGION>RJ</REGION>
			<POSTALCODE>02389-673</POSTALCODE>
			<COUNTRY>Brazil</COUNTRY>
			<PHONE>(21) 555-4252</PHONE>
			<FAX>(21) 555-4545</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>QUEEN</CUSTOMERID>
			<COMPANYNAME>Queen Cozinha</COMPANYNAME>
			<CONTACTNAME>Lúcia Carvalho</CONTACTNAME>
			<CONTACTTITLE>Marketing Assistant</CONTACTTITLE>
			<ADDRESS>Alameda dos Canàrios, 891</ADDRESS>
			<CITY>Sao Paulo</CITY>
			<REGION>SP</REGION>
			<POSTALCODE>05487-020</POSTALCODE>
			<COUNTRY>Brazil</COUNTRY>
			<PHONE>(11) 555-1189</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>QUICK</CUSTOMERID>
			<COMPANYNAME>QUICK-Stop</COMPANYNAME>
			<CONTACTNAME>Horst Kloss</CONTACTNAME>
			<CONTACTTITLE>Accounting Manager</CONTACTTITLE>
			<ADDRESS>Taucherstraße 10</ADDRESS>
			<CITY>Cunewalde</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>01307</POSTALCODE>
			<COUNTRY>Germany</COUNTRY>
			<PHONE>0372-035188</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>RANCH</CUSTOMERID>
			<COMPANYNAME>Rancho grande</COMPANYNAME>
			<CONTACTNAME>Sergio Gutiérrez</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>Av. del Libertador 900</ADDRESS>
			<CITY>Buenos Aires</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>1010</POSTALCODE>
			<COUNTRY>Argentina</COUNTRY>
			<PHONE>(1) 123-5555</PHONE>
			<FAX>(1) 123-5556</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>RATTC</CUSTOMERID>
			<COMPANYNAME>Rattlesnake Canyon Grocery</COMPANYNAME>
			<CONTACTNAME>Paula Wilson</CONTACTNAME>
			<CONTACTTITLE>Assistant Sales Representative</CONTACTTITLE>
			<ADDRESS>2817 Milton Dr.</ADDRESS>
			<CITY>Albuquerque</CITY>
			<REGION>NM</REGION>
			<POSTALCODE>87110</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
			<PHONE>(505) 555-5939</PHONE>
			<FAX>(505) 555-3620</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>REGGC</CUSTOMERID>
			<COMPANYNAME>Reggiani Caseifici</COMPANYNAME>
			<CONTACTNAME>Maurizio Moroni</CONTACTNAME>
			<CONTACTTITLE>Sales Associate</CONTACTTITLE>
			<ADDRESS>Strada Provinciale 124</ADDRESS>
			<CITY>Reggio Emilia</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>42100</POSTALCODE>
			<COUNTRY>Italy</COUNTRY>
			<PHONE>0522-556721</PHONE>
			<FAX>0522-556722</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>RICAR</CUSTOMERID>
			<COMPANYNAME>Ricardo Adocicados</COMPANYNAME>
			<CONTACTNAME>Janete Limeira</CONTACTNAME>
			<CONTACTTITLE>Assistant Sales Agent</CONTACTTITLE>
			<ADDRESS>Av. Copacabana, 267</ADDRESS>
			<CITY>Rio de Janeiro</CITY>
			<REGION>RJ</REGION>
			<POSTALCODE>02389-890</POSTALCODE>
			<COUNTRY>Brazil</COUNTRY>
			<PHONE>(21) 555-3412</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>RICSU</CUSTOMERID>
			<COMPANYNAME>Richter Supermarkt</COMPANYNAME>
			<CONTACTNAME>Michael Holz</CONTACTNAME>
			<CONTACTTITLE>Sales Manager</CONTACTTITLE>
			<ADDRESS>Grenzacherweg 237</ADDRESS>
			<CITY>Genève</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>1203</POSTALCODE>
			<COUNTRY>Switzerland</COUNTRY>
			<PHONE>0897-034214</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>ROMEY</CUSTOMERID>
			<COMPANYNAME>Romero y tomillo</COMPANYNAME>
			<CONTACTNAME>Alejandra Camino</CONTACTNAME>
			<CONTACTTITLE>Accounting Manager</CONTACTTITLE>
			<ADDRESS>Gran Vía, 1</ADDRESS>
			<CITY>Madrid</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>28001</POSTALCODE>
			<COUNTRY>Spain</COUNTRY>
			<PHONE>(91) 745 6200</PHONE>
			<FAX>(91) 745 6210</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>SANTG</CUSTOMERID>
			<COMPANYNAME>Santé Gourmet</COMPANYNAME>
			<CONTACTNAME>Jonas Bergulfsen</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>Erling Skakkes gate 78</ADDRESS>
			<CITY>Stavern</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>4110</POSTALCODE>
			<COUNTRY>Norway</COUNTRY>
			<PHONE>07-98 92 35</PHONE>
			<FAX>07-98 92 47</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>SAVEA</CUSTOMERID>
			<COMPANYNAME>Save-a-lot Markets</COMPANYNAME>
			<CONTACTNAME>Jose Pavarotti</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>187 Suffolk Ln.</ADDRESS>
			<CITY>Boise</CITY>
			<REGION>ID</REGION>
			<POSTALCODE>83720</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
			<PHONE>(208) 555-8097</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>SEVES</CUSTOMERID>
			<COMPANYNAME>Seven Seas Imports</COMPANYNAME>
			<CONTACTNAME>Hari Kumar</CONTACTNAME>
			<CONTACTTITLE>Sales Manager</CONTACTTITLE>
			<ADDRESS>90 Wadhurst Rd.</ADDRESS>
			<CITY>London</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>OX15 4NB</POSTALCODE>
			<COUNTRY>UK</COUNTRY>
			<PHONE>(171) 555-1717</PHONE>
			<FAX>(171) 555-5646</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>SIMOB</CUSTOMERID>
			<COMPANYNAME>Simons bistro</COMPANYNAME>
			<CONTACTNAME>Jytte Petersen</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>Vinbæltet 34</ADDRESS>
			<CITY>Kobenhavn</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>1734</POSTALCODE>
			<COUNTRY>Denmark</COUNTRY>
			<PHONE>31 12 34 56</PHONE>
			<FAX>31 13 35 57</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>SPECD</CUSTOMERID>
			<COMPANYNAME>Spécialités du monde</COMPANYNAME>
			<CONTACTNAME>Dominique Perrier</CONTACTNAME>
			<CONTACTTITLE>Marketing Manager</CONTACTTITLE>
			<ADDRESS>25, rue Lauriston</ADDRESS>
			<CITY>Paris</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>75016</POSTALCODE>
			<COUNTRY>France</COUNTRY>
			<PHONE>(1) 47.55.60.10</PHONE>
			<FAX>(1) 47.55.60.20</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>SPLIR</CUSTOMERID>
			<COMPANYNAME>Split Rail Beer &amp; Ale</COMPANYNAME>
			<CONTACTNAME>Art Braunschweiger</CONTACTNAME>
			<CONTACTTITLE>Sales Manager</CONTACTTITLE>
			<ADDRESS>P.O. Box 555</ADDRESS>
			<CITY>Lander</CITY>
			<REGION>WY</REGION>
			<POSTALCODE>82520</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
			<PHONE>(307) 555-4680</PHONE>
			<FAX>(307) 555-6525</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>SUPRD</CUSTOMERID>
			<COMPANYNAME>Suprêmes délices</COMPANYNAME>
			<CONTACTNAME>Pascale Cartrain</CONTACTNAME>
			<CONTACTTITLE>Accounting Manager</CONTACTTITLE>
			<ADDRESS>Boulevard Tirou, 255</ADDRESS>
			<CITY>Charleroi</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>B-6000</POSTALCODE>
			<COUNTRY>Belgium</COUNTRY>
			<PHONE>(071) 23 67 22 20</PHONE>
			<FAX>(071) 23 67 22 21</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>THEBI</CUSTOMERID>
			<COMPANYNAME>The Big Cheese</COMPANYNAME>
			<CONTACTNAME>Liz Nixon</CONTACTNAME>
			<CONTACTTITLE>Marketing Manager</CONTACTTITLE>
			<ADDRESS>89 Jefferson Way Suite 2</ADDRESS>
			<CITY>Portland</CITY>
			<REGION>OR</REGION>
			<POSTALCODE>97201</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
			<PHONE>(503) 555-3612</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>THECR</CUSTOMERID>
			<COMPANYNAME>The Cracker Box</COMPANYNAME>
			<CONTACTNAME>Liu Wong</CONTACTNAME>
			<CONTACTTITLE>Marketing Assistant</CONTACTTITLE>
			<ADDRESS>55 Grizzly Peak Rd.</ADDRESS>
			<CITY>Butte</CITY>
			<REGION>MT</REGION>
			<POSTALCODE>59801</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
			<PHONE>(406) 555-5834</PHONE>
			<FAX>(406) 555-8083</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>TOMSP</CUSTOMERID>
			<COMPANYNAME>Toms Spezialitäten</COMPANYNAME>
			<CONTACTNAME>Karin Josephs</CONTACTNAME>
			<CONTACTTITLE>Marketing Manager</CONTACTTITLE>
			<ADDRESS>Luisenstr. 48</ADDRESS>
			<CITY>Münster</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>44087</POSTALCODE>
			<COUNTRY>Germany</COUNTRY>
			<PHONE>0251-031259</PHONE>
			<FAX>0251-035695</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>TORTU</CUSTOMERID>
			<COMPANYNAME>Tortuga Restaurante</COMPANYNAME>
			<CONTACTNAME>Miguel Angel Paolino</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>Avda. Azteca 123</ADDRESS>
			<CITY>México D.F.</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>05033</POSTALCODE>
			<COUNTRY>Mexico</COUNTRY>
			<PHONE>(5) 555-2933</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>TRADH</CUSTOMERID>
			<COMPANYNAME>Tradição Hipermercados</COMPANYNAME>
			<CONTACTNAME>Anabela Domingues</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>Av. Inês de Castro, 414</ADDRESS>
			<CITY>Sao Paulo</CITY>
			<REGION>SP</REGION>
			<POSTALCODE>05634-030</POSTALCODE>
			<COUNTRY>Brazil</COUNTRY>
			<PHONE>(11) 555-2167</PHONE>
			<FAX>(11) 555-2168</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>TRAIH</CUSTOMERID>
			<COMPANYNAME>Trail&#39;s Head Gourmet Provisioners</COMPANYNAME>
			<CONTACTNAME>Helvetius Nagy</CONTACTNAME>
			<CONTACTTITLE>Sales Associate</CONTACTTITLE>
			<ADDRESS>722 DaVinci Blvd.</ADDRESS>
			<CITY>Kirkland</CITY>
			<REGION>WA</REGION>
			<POSTALCODE>98034</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
			<PHONE>(206) 555-8257</PHONE>
			<FAX>(206) 555-2174</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>VAFFE</CUSTOMERID>
			<COMPANYNAME>Vaffeljernet</COMPANYNAME>
			<CONTACTNAME>Palle Ibsen</CONTACTNAME>
			<CONTACTTITLE>Sales Manager</CONTACTTITLE>
			<ADDRESS>Smagsloget 45</ADDRESS>
			<CITY>Århus</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>8200</POSTALCODE>
			<COUNTRY>Denmark</COUNTRY>
			<PHONE>86 21 32 43</PHONE>
			<FAX>86 22 33 44</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>VICTE</CUSTOMERID>
			<COMPANYNAME>Victuailles en stock</COMPANYNAME>
			<CONTACTNAME>Mary Saveley</CONTACTNAME>
			<CONTACTTITLE>Sales Agent</CONTACTTITLE>
			<ADDRESS>2, rue du Commerce</ADDRESS>
			<CITY>Lyon</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>69004</POSTALCODE>
			<COUNTRY>France</COUNTRY>
			<PHONE>78.32.54.86</PHONE>
			<FAX>78.32.54.87</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>VINET</CUSTOMERID>
			<COMPANYNAME>Vins et alcools Chevalier</COMPANYNAME>
			<CONTACTNAME>Paul Henriot</CONTACTNAME>
			<CONTACTTITLE>Accounting Manager</CONTACTTITLE>
			<ADDRESS>59 rue de l&#39;Abbaye</ADDRESS>
			<CITY>Reims</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>51100</POSTALCODE>
			<COUNTRY>France</COUNTRY>
			<PHONE>26.47.15.10</PHONE>
			<FAX>26.47.15.11</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>WANDK</CUSTOMERID>
			<COMPANYNAME>Die Wandernde Kuh</COMPANYNAME>
			<CONTACTNAME>Rita Müller</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>Adenauerallee 900</ADDRESS>
			<CITY>Stuttgart</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>70563</POSTALCODE>
			<COUNTRY>Germany</COUNTRY>
			<PHONE>0711-020361</PHONE>
			<FAX>0711-035428</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>WARTH</CUSTOMERID>
			<COMPANYNAME>Wartian Herkku</COMPANYNAME>
			<CONTACTNAME>Pirkko Koskitalo</CONTACTNAME>
			<CONTACTTITLE>Accounting Manager</CONTACTTITLE>
			<ADDRESS>Torikatu 38</ADDRESS>
			<CITY>Oulu</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>90110</POSTALCODE>
			<COUNTRY>Finland</COUNTRY>
			<PHONE>981-443655</PHONE>
			<FAX>981-443655</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>WELLI</CUSTOMERID>
			<COMPANYNAME>Wellington Importadora</COMPANYNAME>
			<CONTACTNAME>Paula Parente</CONTACTNAME>
			<CONTACTTITLE>Sales Manager</CONTACTTITLE>
			<ADDRESS>Rua do Mercado, 12</ADDRESS>
			<CITY>Resende</CITY>
			<REGION>SP</REGION>
			<POSTALCODE>08737-363</POSTALCODE>
			<COUNTRY>Brazil</COUNTRY>
			<PHONE>(14) 555-8122</PHONE>
			<FAX>.NULL.</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>WHITC</CUSTOMERID>
			<COMPANYNAME>White Clover Markets</COMPANYNAME>
			<CONTACTNAME>Karl Jablonski</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>305 - 14th Ave. S. Suite 3B</ADDRESS>
			<CITY>Seattle</CITY>
			<REGION>WA</REGION>
			<POSTALCODE>98128</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
			<PHONE>(206) 555-4112</PHONE>
			<FAX>(206) 555-4115</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>WILMK</CUSTOMERID>
			<COMPANYNAME>Wilman Kala</COMPANYNAME>
			<CONTACTNAME>Matti Karttunen</CONTACTNAME>
			<CONTACTTITLE>Owner&#47;Marketing Assistant</CONTACTTITLE>
			<ADDRESS>Keskuskatu 45</ADDRESS>
			<CITY>Helsinki</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>21240</POSTALCODE>
			<COUNTRY>Finland</COUNTRY>
			<PHONE>90-224 8858</PHONE>
			<FAX>90-224 8858</FAX>
		</RECORD>

		<RECORD>
			<CUSTOMERID>WOLZA</CUSTOMERID>
			<COMPANYNAME>Wolski  Zajazd</COMPANYNAME>
			<CONTACTNAME>Zbyszek Piestrzeniewicz</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>ul. Filtrowa 68</ADDRESS>
			<CITY>Warszawa</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>01-012</POSTALCODE>
			<COUNTRY>Poland</COUNTRY>
			<PHONE>(26) 642-7012</PHONE>
			<FAX>(26) 642-7012</FAX>
		</RECORD>

	</RECORDS>


</TABLE>

