*--------------------------------------------------------------------------------------------------------------------------------------------------------
* (ES) AUTOGENERADO - ¡¡ATENCIÓN!! - ¡¡NO PENSADO PARA EJECUTAR!! USAR SOLAMENTE PARA INTEGRAR CAMBIOS Y ALMACENAR CON HERRAMIENTAS SCM!!
* (EN) AUTOGENERATED - ATTENTION!! - NOT INTENDED FOR EXECUTION!! USE ONLY FOR MERGING CHANGES AND STORING WITH SCM TOOLS!!
*--------------------------------------------------------------------------------------------------------------------------------------------------------
*< FOXBIN2PRG: Version="1.19" SourceFile="shippers.dbf" /> (Solo para binarios VFP 9 / Only for VFP 9 binaries)
*


<TABLE>
	<MemoFile></MemoFile>
	<CodePage>1252</CodePage>
	<LastUpdate></LastUpdate>
	<Database>northwind.dbc</Database>
	<FileType>0x00000031</FileType>
	<FileType_Descrip>Visual FoxPro, autoincrement enabled</FileType_Descrip>

	<FIELDS>
		<FIELD>
			<Name>SHIPPERID</Name>
			<Type>I</Type>
			<Width>4</Width>
			<Decimals>0</Decimals>
			<Null>.F.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName>SHIPPERS</LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp>__ri_update_shippers()</Upd_Trig_Exp>
			<Del_Trig_Exp>__ri_delete_shippers()</Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>4</Autoinc_Nextval>
			<Autoinc_Step>1</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>COMPANYNAME</Name>
			<Type>C</Type>
			<Width>40</Width>
			<Decimals>0</Decimals>
			<Null>.F.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>PHONE</Name>
			<Type>C</Type>
			<Width>24</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
	</FIELDS>


	<indexFile>SHIPPERS.CDX</indexFile>

	<INDEXES>
		<INDEX>
			<TagName>SHIPPERID</TagName>
			<TagType>PRIMARY</TagType>
			<Key>SHIPPERID</Key>
			<Filter></Filter>
			<Order>ASCENDING</Order>
			<Collate>MACHINE</Collate>
		</INDEX>
	</INDEXES>



	<RECORDS>

		<RECORD>
			<SHIPPERID>1</SHIPPERID>
			<COMPANYNAME>Speedy Express</COMPANYNAME>
			<PHONE>(503) 555-9831</PHONE>
		</RECORD>

		<RECORD>
			<SHIPPERID>2</SHIPPERID>
			<COMPANYNAME>United Package</COMPANYNAME>
			<PHONE>(503) 555-3199</PHONE>
		</RECORD>

		<RECORD>
			<SHIPPERID>3</SHIPPERID>
			<COMPANYNAME>Federal Shipping</COMPANYNAME>
			<PHONE>(503) 555-9931</PHONE>
		</RECORD>

	</RECORDS>


</TABLE>

