*--------------------------------------------------------------------------------------------------------------------------------------------------------
* (ES) AUTOGENERADO - ¡¡ATENCIÓN!! - ¡¡NO PENSADO PARA EJECUTAR!! USAR SOLAMENTE PARA INTEGRAR CAMBIOS Y ALMACENAR CON HERRAMIENTAS SCM!!
* (EN) AUTOGENERATED - ATTENTION!! - NOT INTENDED FOR EXECUTION!! USE ONLY FOR MERGING CHANGES AND STORING WITH SCM TOOLS!!
*--------------------------------------------------------------------------------------------------------------------------------------------------------
*< FOXBIN2PRG: Version="1.19" SourceFile="suppliers.dbf" /> (Solo para binarios VFP 9 / Only for VFP 9 binaries)
*


<TABLE>
	<MemoFile></MemoFile>
	<CodePage>1252</CodePage>
	<LastUpdate></LastUpdate>
	<Database>northwind.dbc</Database>
	<FileType>0x00000031</FileType>
	<FileType_Descrip>Visual FoxPro, autoincrement enabled</FileType_Descrip>

	<FIELDS>
		<FIELD>
			<Name>SUPPLIERID</Name>
			<Type>I</Type>
			<Width>4</Width>
			<Decimals>0</Decimals>
			<Null>.F.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName>SUPPLIERS</LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp>__ri_update_suppliers()</Upd_Trig_Exp>
			<Del_Trig_Exp>__ri_delete_suppliers()</Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>30</Autoinc_Nextval>
			<Autoinc_Step>1</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>COMPANYNAME</Name>
			<Type>C</Type>
			<Width>40</Width>
			<Decimals>0</Decimals>
			<Null>.F.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>CONTACTNAME</Name>
			<Type>C</Type>
			<Width>30</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>CONTACTTITLE</Name>
			<Type>C</Type>
			<Width>30</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>ADDRESS</Name>
			<Type>C</Type>
			<Width>60</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>CITY</Name>
			<Type>C</Type>
			<Width>15</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>REGION</Name>
			<Type>C</Type>
			<Width>15</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>POSTALCODE</Name>
			<Type>C</Type>
			<Width>10</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>COUNTRY</Name>
			<Type>C</Type>
			<Width>15</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>PHONE</Name>
			<Type>C</Type>
			<Width>24</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>FAX</Name>
			<Type>C</Type>
			<Width>24</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>HOMEPAGE</Name>
			<Type>M</Type>
			<Width>4</Width>
			<Decimals>0</Decimals>
			<Null>.T.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
	</FIELDS>


	<indexFile>SUPPLIERS.CDX</indexFile>

	<INDEXES>
		<INDEX>
			<TagName>COMPANYNAM</TagName>
			<TagType>REGULAR</TagType>
			<Key>UPPER(COMPANYNAME)</Key>
			<Filter></Filter>
			<Order>ASCENDING</Order>
			<Collate>MACHINE</Collate>
		</INDEX>
		<INDEX>
			<TagName>POSTALCODE</TagName>
			<TagType>REGULAR</TagType>
			<Key>POSTALCODE</Key>
			<Filter></Filter>
			<Order>ASCENDING</Order>
			<Collate>MACHINE</Collate>
		</INDEX>
		<INDEX>
			<TagName>SUPPLIERID</TagName>
			<TagType>PRIMARY</TagType>
			<Key>SUPPLIERID</Key>
			<Filter></Filter>
			<Order>ASCENDING</Order>
			<Collate>MACHINE</Collate>
		</INDEX>
	</INDEXES>



	<RECORDS>

		<RECORD>
			<SUPPLIERID>1</SUPPLIERID>
			<COMPANYNAME>Exotic Liquids</COMPANYNAME>
			<CONTACTNAME>Charlotte Cooper</CONTACTNAME>
			<CONTACTTITLE>Purchasing Manager</CONTACTTITLE>
			<ADDRESS>49 Gilbert St.</ADDRESS>
			<CITY>London</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>EC1 4SD</POSTALCODE>
			<COUNTRY>UK</COUNTRY>
			<PHONE>(171) 555-2222</PHONE>
			<FAX>.NULL.</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>2</SUPPLIERID>
			<COMPANYNAME>New Orleans Cajun Delights</COMPANYNAME>
			<CONTACTNAME>Shelley Burke</CONTACTNAME>
			<CONTACTTITLE>Order Administrator</CONTACTTITLE>
			<ADDRESS>P.O. Box 78934</ADDRESS>
			<CITY>New Orleans</CITY>
			<REGION>LA</REGION>
			<POSTALCODE>70117</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
			<PHONE>(100) 555-4822</PHONE>
			<FAX>.NULL.</FAX>
			<HOMEPAGE></HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>3</SUPPLIERID>
			<COMPANYNAME>Grandma Kelly&#39;s Homestead</COMPANYNAME>
			<CONTACTNAME>Regina Murphy</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>707 Oxford Rd.</ADDRESS>
			<CITY>Ann Arbor</CITY>
			<REGION>MI</REGION>
			<POSTALCODE>48104</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
			<PHONE>(313) 555-5735</PHONE>
			<FAX>(313) 555-3349</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>4</SUPPLIERID>
			<COMPANYNAME>Tokyo Traders</COMPANYNAME>
			<CONTACTNAME>Yoshi Nagase</CONTACTNAME>
			<CONTACTTITLE>Marketing Manager</CONTACTTITLE>
			<ADDRESS>9-8 Sekimai Musashino-shi</ADDRESS>
			<CITY>Tokyo</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>100</POSTALCODE>
			<COUNTRY>Japan</COUNTRY>
			<PHONE>(03) 3555-5011</PHONE>
			<FAX>.NULL.</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>5</SUPPLIERID>
			<COMPANYNAME>Cooperativa de Quesos &#39;Las Cabras&#39;</COMPANYNAME>
			<CONTACTNAME>Antonio del Valle Saavedra</CONTACTNAME>
			<CONTACTTITLE>Export Administrator</CONTACTTITLE>
			<ADDRESS>Calle del Rosal 4</ADDRESS>
			<CITY>Oviedo</CITY>
			<REGION>Asturias</REGION>
			<POSTALCODE>33007</POSTALCODE>
			<COUNTRY>Spain</COUNTRY>
			<PHONE>(98) 598 76 54</PHONE>
			<FAX>.NULL.</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>6</SUPPLIERID>
			<COMPANYNAME>Mayumi&#39;s</COMPANYNAME>
			<CONTACTNAME>Mayumi Ohno</CONTACTNAME>
			<CONTACTTITLE>Marketing Representative</CONTACTTITLE>
			<ADDRESS>92 Setsuko Chuo-ku</ADDRESS>
			<CITY>Osaka</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>545</POSTALCODE>
			<COUNTRY>Japan</COUNTRY>
			<PHONE>(06) 431-7877</PHONE>
			<FAX>.NULL.</FAX>
			<HOMEPAGE></HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>7</SUPPLIERID>
			<COMPANYNAME>Pavlova, Ltd.</COMPANYNAME>
			<CONTACTNAME>Ian Devling</CONTACTNAME>
			<CONTACTTITLE>Marketing Manager</CONTACTTITLE>
			<ADDRESS>74 Rose St. Moonie Ponds</ADDRESS>
			<CITY>Melbourne</CITY>
			<REGION>Victoria</REGION>
			<POSTALCODE>3058</POSTALCODE>
			<COUNTRY>Australia</COUNTRY>
			<PHONE>(03) 444-2343</PHONE>
			<FAX>(03) 444-6588</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>8</SUPPLIERID>
			<COMPANYNAME>Specialty Biscuits, Ltd.</COMPANYNAME>
			<CONTACTNAME>Peter Wilson</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>29 King&#39;s Way</ADDRESS>
			<CITY>Manchester</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>M14 GSD</POSTALCODE>
			<COUNTRY>UK</COUNTRY>
			<PHONE>(161) 555-4448</PHONE>
			<FAX>.NULL.</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>9</SUPPLIERID>
			<COMPANYNAME>PB Knäckebröd AB</COMPANYNAME>
			<CONTACTNAME>Lars Peterson</CONTACTNAME>
			<CONTACTTITLE>Sales Agent</CONTACTTITLE>
			<ADDRESS>Kaloadagatan 13</ADDRESS>
			<CITY>Göteborg</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>S-345 67</POSTALCODE>
			<COUNTRY>Sweden</COUNTRY>
			<PHONE>031-987 65 43</PHONE>
			<FAX>031-987 65 91</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>10</SUPPLIERID>
			<COMPANYNAME>Refrescos Americanas LTDA</COMPANYNAME>
			<CONTACTNAME>Carlos Diaz</CONTACTNAME>
			<CONTACTTITLE>Marketing Manager</CONTACTTITLE>
			<ADDRESS>Av. das Americanas 12.890</ADDRESS>
			<CITY>Sao Paulo</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>5442</POSTALCODE>
			<COUNTRY>Brazil</COUNTRY>
			<PHONE>(11) 555 4640</PHONE>
			<FAX>.NULL.</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>11</SUPPLIERID>
			<COMPANYNAME>Heli Süßwaren GmbH &amp; Co. KG</COMPANYNAME>
			<CONTACTNAME>Petra Winkler</CONTACTNAME>
			<CONTACTTITLE>Sales Manager</CONTACTTITLE>
			<ADDRESS>Tiergartenstraße 5</ADDRESS>
			<CITY>Berlin</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>10785</POSTALCODE>
			<COUNTRY>Germany</COUNTRY>
			<PHONE>(010) 9984510</PHONE>
			<FAX>.NULL.</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>12</SUPPLIERID>
			<COMPANYNAME>Plutzer Lebensmittelgroßmärkte AG</COMPANYNAME>
			<CONTACTNAME>Martin Bein</CONTACTNAME>
			<CONTACTTITLE>International Marketing Mgr.</CONTACTTITLE>
			<ADDRESS>Bogenallee 51</ADDRESS>
			<CITY>Frankfurt</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>60439</POSTALCODE>
			<COUNTRY>Germany</COUNTRY>
			<PHONE>(069) 992755</PHONE>
			<FAX>.NULL.</FAX>
			<HOMEPAGE></HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>13</SUPPLIERID>
			<COMPANYNAME>Nord-Ost-Fisch Handelsgesellschaft mbH</COMPANYNAME>
			<CONTACTNAME>Sven Petersen</CONTACTNAME>
			<CONTACTTITLE>Coordinator Foreign Markets</CONTACTTITLE>
			<ADDRESS>Frahmredder 112a</ADDRESS>
			<CITY>Cuxhaven</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>27478</POSTALCODE>
			<COUNTRY>Germany</COUNTRY>
			<PHONE>(04721) 8713</PHONE>
			<FAX>(04721) 8714</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>14</SUPPLIERID>
			<COMPANYNAME>Formaggi Fortini s.r.l.</COMPANYNAME>
			<CONTACTNAME>Elio Rossi</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>Viale Dante, 75</ADDRESS>
			<CITY>Ravenna</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>48100</POSTALCODE>
			<COUNTRY>Italy</COUNTRY>
			<PHONE>(0544) 60323</PHONE>
			<FAX>(0544) 60603</FAX>
			<HOMEPAGE></HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>15</SUPPLIERID>
			<COMPANYNAME>Norske Meierier</COMPANYNAME>
			<CONTACTNAME>Beate Vileid</CONTACTNAME>
			<CONTACTTITLE>Marketing Manager</CONTACTTITLE>
			<ADDRESS>Hatlevegen 5</ADDRESS>
			<CITY>Sandvika</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>1320</POSTALCODE>
			<COUNTRY>Norway</COUNTRY>
			<PHONE>(0)2-953010</PHONE>
			<FAX>.NULL.</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>16</SUPPLIERID>
			<COMPANYNAME>Bigfoot Breweries</COMPANYNAME>
			<CONTACTNAME>Cheryl Saylor</CONTACTNAME>
			<CONTACTTITLE>Regional Account Rep.</CONTACTTITLE>
			<ADDRESS>3400 - 8th Avenue Suite 210</ADDRESS>
			<CITY>Bend</CITY>
			<REGION>OR</REGION>
			<POSTALCODE>97101</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
			<PHONE>(503) 555-9931</PHONE>
			<FAX>.NULL.</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>17</SUPPLIERID>
			<COMPANYNAME>Svensk Sjöföda AB</COMPANYNAME>
			<CONTACTNAME>Michael Björn</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>Brovallavägen 231</ADDRESS>
			<CITY>Stockholm</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>S-123 45</POSTALCODE>
			<COUNTRY>Sweden</COUNTRY>
			<PHONE>08-123 45 67</PHONE>
			<FAX>.NULL.</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>18</SUPPLIERID>
			<COMPANYNAME>Aux joyeux ecclésiastiques</COMPANYNAME>
			<CONTACTNAME>Guylène Nodier</CONTACTNAME>
			<CONTACTTITLE>Sales Manager</CONTACTTITLE>
			<ADDRESS>203, Rue des Francs-Bourgeois</ADDRESS>
			<CITY>Paris</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>75004</POSTALCODE>
			<COUNTRY>France</COUNTRY>
			<PHONE>(1) 03.83.00.68</PHONE>
			<FAX>(1) 03.83.00.62</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>19</SUPPLIERID>
			<COMPANYNAME>New England Seafood Cannery</COMPANYNAME>
			<CONTACTNAME>Robb Merchant</CONTACTNAME>
			<CONTACTTITLE>Wholesale Account Agent</CONTACTTITLE>
			<ADDRESS>Order Processing Dept. 2100 Paul Revere Blvd.</ADDRESS>
			<CITY>Boston</CITY>
			<REGION>MA</REGION>
			<POSTALCODE>02134</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
			<PHONE>(617) 555-3267</PHONE>
			<FAX>(617) 555-3389</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>20</SUPPLIERID>
			<COMPANYNAME>Leka Trading</COMPANYNAME>
			<CONTACTNAME>Chandra Leka</CONTACTNAME>
			<CONTACTTITLE>Owner</CONTACTTITLE>
			<ADDRESS>471 Serangoon Loop, Suite #402</ADDRESS>
			<CITY>Singapore</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>0512</POSTALCODE>
			<COUNTRY>Singapore</COUNTRY>
			<PHONE>555-8787</PHONE>
			<FAX>.NULL.</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>21</SUPPLIERID>
			<COMPANYNAME>Lyngbysild</COMPANYNAME>
			<CONTACTNAME>Niels Petersen</CONTACTNAME>
			<CONTACTTITLE>Sales Manager</CONTACTTITLE>
			<ADDRESS>Lyngbysild Fiskebakken 10</ADDRESS>
			<CITY>Lyngby</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>2800</POSTALCODE>
			<COUNTRY>Denmark</COUNTRY>
			<PHONE>43844108</PHONE>
			<FAX>43844115</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>22</SUPPLIERID>
			<COMPANYNAME>Zaanse Snoepfabriek</COMPANYNAME>
			<CONTACTNAME>Dirk Luchte</CONTACTNAME>
			<CONTACTTITLE>Accounting Manager</CONTACTTITLE>
			<ADDRESS>Verkoop Rijnweg 22</ADDRESS>
			<CITY>Zaandam</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>9999 ZZ</POSTALCODE>
			<COUNTRY>Netherlands</COUNTRY>
			<PHONE>(12345) 1212</PHONE>
			<FAX>(12345) 1210</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>23</SUPPLIERID>
			<COMPANYNAME>Karkki Oy</COMPANYNAME>
			<CONTACTNAME>Anne Heikkonen</CONTACTNAME>
			<CONTACTTITLE>Product Manager</CONTACTTITLE>
			<ADDRESS>Valtakatu 12</ADDRESS>
			<CITY>Lappeenranta</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>53120</POSTALCODE>
			<COUNTRY>Finland</COUNTRY>
			<PHONE>(953) 10956</PHONE>
			<FAX>.NULL.</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>24</SUPPLIERID>
			<COMPANYNAME>G&#39;day, Mate</COMPANYNAME>
			<CONTACTNAME>Wendy Mackenzie</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>170 Prince Edward Parade Hunter&#39;s Hill</ADDRESS>
			<CITY>Sydney</CITY>
			<REGION>NSW</REGION>
			<POSTALCODE>2042</POSTALCODE>
			<COUNTRY>Australia</COUNTRY>
			<PHONE>(02) 555-5914</PHONE>
			<FAX>(02) 555-4873</FAX>
			<HOMEPAGE></HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>25</SUPPLIERID>
			<COMPANYNAME>Ma Maison</COMPANYNAME>
			<CONTACTNAME>Jean-Guy Lauzon</CONTACTNAME>
			<CONTACTTITLE>Marketing Manager</CONTACTTITLE>
			<ADDRESS>2960 Rue St. Laurent</ADDRESS>
			<CITY>Montréal</CITY>
			<REGION>Québec</REGION>
			<POSTALCODE>H1J 1C3</POSTALCODE>
			<COUNTRY>Canada</COUNTRY>
			<PHONE>(514) 555-9022</PHONE>
			<FAX>.NULL.</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>26</SUPPLIERID>
			<COMPANYNAME>Pasta Buttini s.r.l.</COMPANYNAME>
			<CONTACTNAME>Giovanni Giudici</CONTACTNAME>
			<CONTACTTITLE>Order Administrator</CONTACTTITLE>
			<ADDRESS>Via dei Gelsomini, 153</ADDRESS>
			<CITY>Salerno</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>84100</POSTALCODE>
			<COUNTRY>Italy</COUNTRY>
			<PHONE>(089) 6547665</PHONE>
			<FAX>(089) 6547667</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>27</SUPPLIERID>
			<COMPANYNAME>Escargots Nouveaux</COMPANYNAME>
			<CONTACTNAME>Marie Delamare</CONTACTNAME>
			<CONTACTTITLE>Sales Manager</CONTACTTITLE>
			<ADDRESS>22, rue H. Voiron</ADDRESS>
			<CITY>Montceau</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>71300</POSTALCODE>
			<COUNTRY>France</COUNTRY>
			<PHONE>85.57.00.07</PHONE>
			<FAX>.NULL.</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>28</SUPPLIERID>
			<COMPANYNAME>Gai pâturage</COMPANYNAME>
			<CONTACTNAME>Eliane Noz</CONTACTNAME>
			<CONTACTTITLE>Sales Representative</CONTACTTITLE>
			<ADDRESS>Bat. B 3, rue des Alpes</ADDRESS>
			<CITY>Annecy</CITY>
			<REGION>.NULL.</REGION>
			<POSTALCODE>74000</POSTALCODE>
			<COUNTRY>France</COUNTRY>
			<PHONE>38.76.98.06</PHONE>
			<FAX>38.76.98.58</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

		<RECORD>
			<SUPPLIERID>29</SUPPLIERID>
			<COMPANYNAME>Forêts d&#39;érables</COMPANYNAME>
			<CONTACTNAME>Chantal Goulet</CONTACTNAME>
			<CONTACTTITLE>Accounting Manager</CONTACTTITLE>
			<ADDRESS>148 rue Chasseur</ADDRESS>
			<CITY>Ste-Hyacinthe</CITY>
			<REGION>Québec</REGION>
			<POSTALCODE>J2S 7S8</POSTALCODE>
			<COUNTRY>Canada</COUNTRY>
			<PHONE>(514) 555-2955</PHONE>
			<FAX>(514) 555-2921</FAX>
			<HOMEPAGE>.NULL.</HOMEPAGE>
		</RECORD>

	</RECORDS>


</TABLE>

